import "@repo/ui/globals.css";

import { type Metadata } from "next";
import { Roboto } from "next/font/google";
import { APP_NAME } from "@/constants";

import { Providers } from "@/components/providers";

export const metadata: Metadata = {
  title: APP_NAME,
  description: "Generated by create-t3-app",
};

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${roboto.variable}`} suppressHydrationWarning>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
