import { authClient } from "./client";

export const {
  signIn,
  signOut,
  useSession,
  admin,
  apiKey,
  organization,
  multiSession,
  twoFactor,
  signUp,
  accountInfo,
  changeEmail,
  changePassword,
  deleteUser,
  emailOtp,
  forgetPassword,
  getAccessToken,
  getSession,
  isUsernameAvailable,
  linkSocial,
  listAccounts,
  listSessions,
  magicLink,
  refreshToken,
  requestPasswordReset,
  resetPassword,
  revokeOtherSessions,
  revokeSession,
  revokeSessions,
  sendVerificationEmail,
  unlinkAccount,
  updateUser,
  useActiveMember,
  useActiveOrganization,
  useListOrganizations,
  verifyEmail,
} = authClient;
